#!/usr/bin/env bash

# Source configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."
source "${PROJECT_ROOT}/config.sh"

# Check local process
PID=$(ps -aux | grep -e "[p]ython.*${APP_ENTRY}" | awk 'FNR == 1 {print $2}')

# Check if process is running
if [ -z "$PID" ]; then
    echo "Application is not running."
    exit 0
fi

echo "Application is running (PID: $PID)."
exit 0
